---
- name: Verify the range of validators is provided
  assert:
    that:
      - dist_validators_start is defined
      - dist_validators_end is defined
    fail_msg: 'No start or end of validators provided!'
    quiet: true

- name: Verify the destination for validators is provided
  assert:
    that: dist_validators_data_path is defined
    fail_msg: 'Beacon node folder not provided!'
    quiet: true

- when: ansible_system == "Linux"
  include_tasks: linux/clone.yml
- when: ansible_system == "Win32NT"
  include_tasks: windows/clone.yml
- when: ansible_system == "Darwin"
  include_tasks: macos/clone.yml

- when: ansible_system == "Linux"
  include_tasks: linux/copy.yml
- when: ansible_system == "Win32NT"
  include_tasks: windows/copy.yml
- when: ansible_system == "Darwin"
  include_tasks: macos/copy.yml
