---
- name: Verify the range of validators is provided
  assert:
    that:
      - dist_validators_start is defined
      - dist_validators_end is defined
    fail_msg: 'No start or end of validators provided!'
    quiet: true

- name: Verify the destination for validators is provided
  assert:
    that:
      - dist_validators_sec_path is defined
      - dist_validators_val_path is defined
    fail_msg: 'Destination folders not provided!'
    quiet: true

- include_tasks: '{{ ansible_system|lower }}/clone.yml'
- include_tasks: '{{ ansible_system|lower }}/copy.yml'
