---
- name: Remove validators/secrets folders
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ dist_validators_wallet_path }}'
    - '{{ dist_validators_secret_path }}'

- name: Create validators/secrets folders
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: '{{ dist_validators_user | mandatory }}'
    group: '{{ dist_validators_group | mandatory }}'
    mode: 0700
  with_items:
    - '{{ dist_validators_wallet_path }}'
    - '{{ dist_validators_secret_path }}'

- name: Copy over validators
  command: |
    rsync -ru --delete --exclude="slashing_protection.sqlite3*" \
      {{ new_validators | join(" ") }} '{{ dist_validators_wallet_path }}/'
  args:
    chdir: '{{ dist_validators_repo_path }}/{{ dist_validators_name | mandatory }}/validators'

- name: Copy over secrets
  command: |
    rsync -ru --delete {{ new_secrets | join(" ") }} '{{ dist_validators_secret_path }}/'
  args:
    chdir: '{{ dist_validators_repo_path }}/{{ dist_validators_name | mandatory }}/secrets'

- name: Adjust folder owner and group
  command: |
    chown {{ dist_validators_user }}:{{ dist_validators_group }} -R '{{ dist_validators_data_path }}'
  args: { warn: false }

- name: Adjust validators dir permissions
  shell: 'find "{{ dist_validators_wallet_path }}" -type d -exec chmod 0700 -R {} \;'
  args: { warn: false }

- name: Adjust validators file permissions
  shell: 'find "{{ dist_validators_wallet_path }}" -type f -exec chmod 0600 {} \;'
  args: { warn: false }

- name: Adjust secrets permissions
  shell: 'find "{{ dist_validators_secret_path }}" -type f -exec chmod 0600 {} \;'
  args: { warn: false }

- name: Return list of deployed validators
  set_fact:
    # Available for beacon-node role to display. Indicates success.
    dist_validators_deployed: '{{ new_validators }}'
