---
- name: Remove validators/secrets folders
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ dist_validators_wallet_path }}'
    - '{{ dist_validators_secret_path }}'

- name: Create validators/secrets folders
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: dockremap
    group: docker
    mode: 0700
  with_items:
    - '{{ dist_validators_wallet_path }}'
    - '{{ dist_validators_secret_path }}'

- name: Copy over validators
  command: |
    rsync -ru --delete --exclude="slashing_protection.sqlite3*" \
      {{ new_validators | join(" ") }} '{{ dist_validators_wallet_path }}/'
  args:
    chdir: '{{ dist_validators_path }}'

- name: Copy over secrets
  command: |
    rsync -ru --delete {{ new_secrets | join(" ") }} '{{ dist_validators_secrets_path }}/'
  args:
    chdir: '{{ dist_validators_secrets_path }}'

- name: Adjust folder owner and group
  command: 'chown dockremap:docker -R {{ dist_validators_data_path }}'
  args: { warn: false }

- name: Adjust validators dir permissions
  shell: 'find "{{ dist_validators_wallet_path }}" -type d -exec chmod 0700 -R {} \;'
  args: { warn: false }

- name: Adjust validators file permissions
  shell: 'find "{{ dist_validators_wallet_path }}" -type f -exec chmod 0600 {} \;'
  args: { warn: false }

- name: Adjust secrets permissions
  shell: 'find "{{ dist_validators_secrets_path }}" -type f -exec chmod 0600 {} \;'
  args: { warn: false }
