---
- name: Copy over distributor script
  copy: 
    src: 'dist_validators.py'
    dest: '{{ dist_validators_repo_user_path }}/dist_validators.py'
    owner: '{{ dist_validators_repo_user }}'
    group: '{{ dist_validators_admin_group }}'
    mode: 0755

- name: Copy over validators and secrets
  become_user: '{{ dist_validators_repo_user }}'
  register: dist_validators_run
  command: >-
    '{{ dist_validators_repo_user_path }}/dist_validators.py'
      --input-sec={{ dist_validators_deposits_path | mandatory }}/secrets
      --input-val={{ dist_validators_deposits_path | mandatory }}/validators
      --output-sec={{ dist_validators_sec_path | mandatory }}
      --output-val={{ dist_validators_val_path | mandatory }}
      --start={{ dist_validators_start | mandatory }}
      --end={{ dist_validators_end | mandatory }}
      --log-level={{ dist_validators_log_level }}
      {% if dist_validators_purge_enabled %}--purge{% endif %}
      --print-count

- name: Extract number of deployed validators
  when: dist_validators_run.stdout != ""
  set_fact:
    dist_validators_deployed: "{{ dist_validators_run.stdout | int }}"
