---
- name: Copy over distributor script
  win_copy:
    src: 'dist_validators.py'
    dest: '{{ dist_validators_repo_user_path }}/dist_validators.py'

# WARNING: Make sure there's no host-wide become-user set.
- name: Copy over validators and secrets
  become: true
  become_user: '{{ dist_validators_repo_user }}'
  vars:
    ansible_become_user: '{{ dist_validators_repo_user | mandatory }}'
    ansible_become_pass: '{{ dist_validators_repo_user_pass | mandatory }}'
  register: dist_validators_run
  win_shell: >-
    python3 {{ dist_validators_repo_user_path }}/dist_validators.py \
      --input-sec={{ dist_validators_deposits_path | mandatory }}/secrets \
      --input-val={{ dist_validators_deposits_path | mandatory }}/validators \
      --output-sec={{ dist_validators_sec_path | mandatory }} \
      --output-val={{ dist_validators_val_path | mandatory }} \
      --start={{ dist_validators_start | mandatory }} \
      --end={{ dist_validators_end | mandatory }} \
      --log-level={{ dist_validators_log_level }} \
      --print-count

- name: Extract number of deployed validators
  when: dist_validators_run.stdout != ""
  set_fact:
    dist_validators_deployed: "{{ dist_validators_run.stdout | int }}"
