---
- name: Copy over distributor script
  win_copy:
    src: 'dist_validators.py'
    dest: '{{ dist_validators_repo_user_path }}/dist_validators.py'

- name: Copy over validators and secrets
  become: true
  become_user: '{{ dist_validators_repo_user }}'
  vars:
    ansible_become_user: '{{ dist_validators_repo_user }}'
    ansible_become_pass: '{{ dist_validators_repo_user_pass | mandatory }}'
  register: dist_validators_run
  win_shell: >-
    python3 {{ dist_validators_repo_user_path }}/dist_validators.py \
      --input={{ dist_validators_deposits_path | mandatory }} \
      --output={{ dist_validators_data_path | mandatory }} \
      --start={{ dist_validators_start | mandatory }} \
      --end={{ dist_validators_end | mandatory }} \
      --log-level={{ dist_validators_log_level }} \
      --print-count

- name: Extract numberof deployed validators
  when: dist_validators_run.stdout != ""
  set_fact:
    dist_validators_deployed: "{{ dist_validators_run.stdout | int }}"
